// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCStore.Models.DataLayer;

#nullable disable

namespace PCStore.Migrations
{
    [DbContext(typeof(PCStoreContext))]
    [Migration("20231215203731_ProductsAdded")]
    partial class ProductsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCStore.Models.DomainModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "",
                            CategoryName = "Motherboard"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "",
                            CategoryName = "Processor"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "",
                            CategoryName = "Memory"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "",
                            CategoryName = "Video Graphics Card"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "",
                            CategoryName = "Storage"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "",
                            CategoryName = "Accessory"
                        });
                });

            modelBuilder.Entity("PCStore.Models.DomainModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsProductInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProductOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageThumbnailURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryID = 1,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "Buffed and ready with more power, robust cooling, and flexible I/O to scale up your rig at will. The ROG Maximus Z790 Hero puts it all at your disposal together with an arsenal of features and utilities to truly express the PC builder, overclocker, and gaming hero in you.",
                            ProductImageThumbnailURL = "/images/product01.jpg",
                            ProductImageURL = "/images/product01.jpg",
                            ProductName = "ASUS ROG Maximus Z790 Hero",
                            ProductPrice = 609.99000000000001
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryID = 1,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Featurign Core Boost Technology, 6 layer PCB, and the highest quality power delivery components, the MSI MAG B550 Tomahawk gives you unmatched performance at an unbeatable price.",
                            ProductImageThumbnailURL = "/images/product02.jpg",
                            ProductImageURL = "/images/product02.jpg",
                            ProductName = "MSI MAG B550 Tomahawk",
                            ProductPrice = 169.99000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryID = 1,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "ROG Strix Z690-E Gaming Wi-Fi puts 12th Gen Intel® Core™ processors at center stage, with beefed-up power delivery, cooling, cutting-edge connectivity options, and a range of accoutrements that effortlessly propel builds to maximum performance. This series flagship is your ticket to next-level gaming.",
                            ProductImageThumbnailURL = "/images/product03.jpg",
                            ProductImageURL = "/images/product03.jpg",
                            ProductName = "ASUS ROG Strix Z690-E",
                            ProductPrice = 279.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryID = 2,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Get the competitive edge with 12 cores, 24 threads, boost clocks of up to 4.8GHz2 and 70MB of cache.",
                            ProductImageThumbnailURL = "/images/product04.jpg",
                            ProductImageURL = "/images/product04.jpg",
                            ProductName = "AMD Ryzen 9 5900X",
                            ProductPrice = 549.99000000000001
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryID = 2,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Blazing-fast clock speeds and a revolutionary core architecture allow you to seamlessly chat, stream and record without sacrificing gameplay.",
                            ProductImageThumbnailURL = "/images/product05.jpg",
                            ProductImageURL = "/images/product05.jpg",
                            ProductName = "Intel Core i7-12700K",
                            ProductPrice = 449.99000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryID = 2,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "With the highest clock speeds and a groundbreaking new architecture, you’ll be able to push your gameplay to new heights while secondary apps run seamlessly in the background.",
                            ProductImageThumbnailURL = "/images/product06.jpg",
                            ProductImageURL = "/images/product06.jpg",
                            ProductName = "Intel Core i9-12700K",
                            ProductPrice = 649.99000000000001
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryID = 3,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "As the latest addition to the classic RipJaws family, RipJaws V series DDR4 memory is designed for sleek aesthetics and performance. Ripjaws V is the ideal choice for building a new performance system or for DRAM memory upgrade.",
                            ProductImageThumbnailURL = "/images/product07.jpg",
                            ProductImageURL = "/images/product07.jpg",
                            ProductName = "G.SKILL Ripjaws V Series 32 GB",
                            ProductPrice = 64.989999999999995
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryID = 3,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Speed up loading times, boost system responsiveness, and improve your computers ability to handle greater workloads with Nemix Ram's 32GB kit.",
                            ProductImageThumbnailURL = "/images/product08.jpg",
                            ProductImageURL = "/images/product08.jpg",
                            ProductName = "Nemix Ram 32GB Kit",
                            ProductPrice = 97.989999999999995
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryID = 3,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "VENGEANCE LPX memory is designed for high-performance overclocking. Whether you're breaking your own records or you're simply building a dream gaming rig, you can count on CORSAIR memory.",
                            ProductImageThumbnailURL = "/images/product09.jpg",
                            ProductImageURL = "/images/product09.jpg",
                            ProductName = "Corsair Vengeance LPX 16GB",
                            ProductPrice = 51.990000000000002
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryID = 4,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Granting peak performance at an affordable price, the best selling MSI Ventus GeForce RTX 3060 is a must have for newcomers and enthusiasts alike.",
                            ProductImageThumbnailURL = "/images/product10.jpg",
                            ProductImageURL = "/images/product10.jpg",
                            ProductName = "MSI Ventus GeForce RTX 3060",
                            ProductPrice = 289.99000000000001
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryID = 4,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Looking to power up your rig? Look no further than the GIGABYTE Gaming OC RTX 3070. Offering NVIDIA multiprocessors, Windforce cooling systems, and a 1815 MHz core clock, this card offers unparalleled performance.",
                            ProductImageThumbnailURL = "/images/product11.jpg",
                            ProductImageURL = "/images/product11.jpg",
                            ProductName = "GIGABYTE Gaming OC GeForce 3070",
                            ProductPrice = 569.99000000000001
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryID = 4,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Get equipped to play the newest games at the highest settings with 12GB of GDDR6 memory and 40 enhanced compute units delivering 1440p gaming at ultra settings with smooth framerates and maximum visual settings.",
                            ProductImageThumbnailURL = "/images/product12.jpg",
                            ProductImageURL = "/images/product12.jpg",
                            ProductName = "ASRock Radeon RX 6700 XT",
                            ProductPrice = 329.99000000000001
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "Purpose built for multi-user NAS environments, Seagate IronWolf drives are perfect for teams needing to store more and work faster.",
                            ProductImageThumbnailURL = "/images/product13.jpg",
                            ProductImageURL = "/images/product13.jpg",
                            ProductName = "Seagate IronWolf 12TB NAS Harddrive Internal HDD",
                            ProductPrice = 359.99000000000001
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Perfect for reliable, everyday computing with Western Digital quality and reliability.",
                            ProductImageThumbnailURL = "/images/product14.jpg",
                            ProductImageURL = "/images/product14.jpg",
                            ProductName = "WD Blue 500GB Desktop Hard Disk Drive",
                            ProductPrice = 59.990000000000002
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Cost effective storage for laptop or desktop computers. Store all your games, music, movies and more with up to 8TB of storage.",
                            ProductImageThumbnailURL = "/images/product15.jpg",
                            ProductImageURL = "/images/product15.jpg",
                            ProductName = "Seagate BarraCude 8TB SATA Internal Hard Drive",
                            ProductPrice = 189.99000000000001
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "Compatible with PC, desktop, laptop, Xbox One, and PS4. Plug and play - no software to install and ready to use.",
                            ProductImageThumbnailURL = "/images/product16.jpg",
                            ProductImageURL = "/images/product16.jpg",
                            ProductName = "UnionSine 1TB Ultra Slim Portable External Hard Drive",
                            ProductPrice = 55.990000000000002
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "With massive capacity and innovative technology advancements, this Exos X18 enterprise hard drive is engineered to address the needs of the hyperscale storage market.",
                            ProductImageThumbnailURL = "/images/product17.jpg",
                            ProductImageURL = "/images/product17.jpg",
                            ProductName = "Seagate 18TB Exos Enterprise Hard Drive HDD",
                            ProductPrice = 399.99000000000001
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Compatible with all of your devices, the T7 Shield features read/write speeds of up to 1,000 MB/s and a durable design to resist wear and damage.",
                            ProductImageThumbnailURL = "/images/product18.jpg",
                            ProductImageURL = "/images/product18.jpg",
                            ProductName = "Samsung T7 Shield 4TB External Solid State Drive",
                            ProductPrice = 249.99000000000001
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "With excellent performance including read speeds of up to $5,000MB/s, this drive enhances the speed and performance of your entire system.",
                            ProductImageThumbnailURL = "/images/product19.jpg",
                            ProductImageURL = "/images/product19.jpg",
                            ProductName = "T-Force Cardea 1TB NVME Internal Solid State Drive",
                            ProductPrice = 74.989999999999995
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "With blistering speeds of up to 12,000MB/s, experience performance like you never have before. Perfect for the ultimate gaming and creative computer.",
                            ProductImageThumbnailURL = "/images/product20.jpg",
                            ProductImageURL = "/images/product20.jpg",
                            ProductName = "Crucial T700 2TB NVME Internal Solid State Drive",
                            ProductPrice = 295.99000000000001
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryID = 5,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "KingSpec NVME SSD is the ideal data storage solution for your desktop or laptop, drastically improving performace and efficiency.",
                            ProductImageThumbnailURL = "/images/product21.jpg",
                            ProductImageURL = "/images/product21.jpg",
                            ProductName = "KingSpec 1TB NVME Internal Solid State Drive",
                            ProductPrice = 121.98999999999999
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Keep your system looking and running cool with the premier RBG lighting fans on the market.",
                            ProductImageThumbnailURL = "/images/product22.jpg",
                            ProductImageURL = "/images/product22.jpg",
                            ProductName = "Corsair iCUE RGB Elite Triple Fan Kit Black",
                            ProductPrice = 51.990000000000002
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "Keep your system looking and running cool with the premier RBG lighting fans on the market.",
                            ProductImageThumbnailURL = "/images/product23.jpg",
                            ProductImageURL = "/images/product23.jpg",
                            ProductName = "Corsair iCUE RGB Elite Triple Fan Kit White",
                            ProductPrice = 79.989999999999995
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Premium quiet fan with advanced flow channels and acoustic optimisation for quiet cooling.",
                            ProductImageThumbnailURL = "/images/product24.jpg",
                            ProductImageURL = "/images/product24.jpg",
                            ProductName = "Noctua Premium Quiet Fan - Brown",
                            ProductPrice = 23.949999999999999
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "The final component of your gaming system. A good monitor elevates the performance of all of your PC components. GIGABYTE gaming monitors offer the best boost in the business.",
                            ProductImageThumbnailURL = "/images/product25.jpg",
                            ProductImageURL = "/images/product25.jpg",
                            ProductName = "GIGABYTE G27Q 27 inch 144Hz 1440p Gaming Monitor",
                            ProductPrice = 249.99000000000001
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "32 Inch display with ultrafast 175Hz refresh rate designed for the best gameplay. G-Sync compatibility offers seamless, tear-free experiences by default.",
                            ProductImageThumbnailURL = "/images/product26.jpg",
                            ProductImageURL = "/images/product26.jpg",
                            ProductName = "ASUS 32 inch 1440p G-Sync Gaming Monitor",
                            ProductPrice = 529.99000000000001
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Ultra HD 3840 x 2160 Resultion and a 178 degree wide viewing angle offer unparalleled viewing experience.",
                            ProductImageThumbnailURL = "/images/product27.jpg",
                            ProductImageURL = "/images/product27.jpg",
                            ProductName = "Z-EDGE U27P4K 27 inch IPS 4K Monitor",
                            ProductPrice = 249.99000000000001
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "With rapid response and a sleek, stylish design, the MK710 is perfect for home desktops. Features up to three-year battery life.",
                            ProductImageThumbnailURL = "/images/product28.jpg",
                            ProductImageURL = "/images/product28.jpg",
                            ProductName = "Logitech MK710 Wireless Keyboard and Mouse Combo",
                            ProductPrice = 79.989999999999995
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = false,
                            ProductDescription = "Made with recycled plastic, Pebble 2's minimalist, slim design makes for an iconic and portable accessory. Pairs with up to three devices via bluetooth.",
                            ProductImageThumbnailURL = "/images/product29.jpg",
                            ProductImageURL = "/images/product29.jpg",
                            ProductName = "Logitech Pebble 2 Combo Wireless Keyboard and Mouse",
                            ProductPrice = 59.990000000000002
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryID = 6,
                            IsProductInStock = true,
                            IsProductOnSale = true,
                            ProductDescription = "Experience the feel of a mechanical keyboard with the responsiveness of a membrane keyboard. Features accurate feedback, reduced noise, and enhanced comfort.",
                            ProductImageThumbnailURL = "/images/product30.jpg",
                            ProductImageURL = "/images/product30.jpg",
                            ProductName = "Rosewill NEON K42 Wired Mechanical Gaming Keyboard",
                            ProductPrice = 49.990000000000002
                        });
                });

            modelBuilder.Entity("PCStore.Models.DomainModels.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartItemId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("PCStore.Models.DomainModels.Product", b =>
                {
                    b.HasOne("PCStore.Models.DomainModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PCStore.Models.DomainModels.ShoppingCartItem", b =>
                {
                    b.HasOne("PCStore.Models.DomainModels.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PCStore.Models.DomainModels.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
